FROM debian:bullseye-slim

# Install DuckDB and curl
RUN apt-get update && apt-get install -y wget unzip \
    && wget https://github.com/duckdb/duckdb/releases/download/v1.1.3/duckdb_cli-linux-amd64.zip \
    && unzip duckdb_cli-linux-amd64.zip -d /usr/local/bin \
    && rm duckdb_cli-linux-amd64.zip \
    && apt-get clean

# Create a startup script to install extensions
RUN echo "install httpfs; install iceberg;" > /root/.duckdbrc

ENTRYPOINT ["tail", "-f", "/dev/null"]